/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Employee;
import model.EmployeeDirectory;

/**
 *
 * @author ashwini
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    // Creating reference variable for ArrayList.
    EmployeeDirectory directory;
    
    public CreateJPanel() {
        initComponents();
    }
    public CreateJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagepathField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        teaminfoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        employeeidField = new javax.swing.JTextField();
        levelField = new javax.swing.JTextField();
        teaminfoField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        phonenumberLabel = new javax.swing.JLabel();
        phonenumberField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        startDatePicker = new org.jdesktop.swingx.JXDatePicker();
        mRadioButton = new javax.swing.JRadioButton();
        fRadioButton = new javax.swing.JRadioButton();
        nameLabel = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();
        employeeidLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Directory ");

        genderLabel.setText("Gender:");

        startdateLabel.setText("Start Date:");

        levelLabel.setText("Level:");

        teaminfoLabel.setText("Team Info:");

        titleLabel.setText("Position/Title :");

        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        phonenumberLabel.setText("Phone Number:");

        emailLabel.setText("Email :");

        mRadioButton.setText("Male");

        fRadioButton.setText("Female");

        nameLabel.setText("Name:");

        imageButton.setText("Upload Image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        employeeidLabel.setText("EmployeeId:");

        ageLabel.setText("Age:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(241, 241, 241))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameLabel)
                        .addComponent(employeeidLabel)
                        .addComponent(ageLabel)
                        .addComponent(genderLabel)
                        .addComponent(startdateLabel)
                        .addComponent(levelLabel)
                        .addComponent(teaminfoLabel)
                        .addComponent(titleLabel)
                        .addComponent(phonenumberLabel)
                        .addComponent(emailLabel)
                        .addComponent(imageButton)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(159, 159, 159)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameField)
                        .addComponent(employeeidField)
                        .addComponent(ageField)
                        .addComponent(levelField)
                        .addComponent(teaminfoField)
                        .addComponent(titleField)
                        .addComponent(phonenumberField)
                        .addComponent(emailField)
                        .addComponent(startDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                            .addComponent(fRadioButton))
                        .addComponent(imagepathField))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(562, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employeeidLabel)
                        .addComponent(employeeidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageLabel)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderLabel)
                        .addComponent(mRadioButton)
                        .addComponent(fRadioButton))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startdateLabel)
                        .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(levelLabel)
                        .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teaminfoLabel)
                        .addComponent(teaminfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLabel)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phonenumberLabel)
                        .addComponent(phonenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageButton)
                        .addComponent(imagepathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(51, 51, 51)
                    .addComponent(saveButton)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Function Code for Save Button
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        // Performing Following Validation on Input Text Fields -
        // 1. Check if input value is empty.
        // 2. Check if input datatype is not matching suppose input value(like String).
        // 3. Check if length of input value for phone number is less or more than 10.
        // 4. Check if input value for Email has @.
        
        int val = 0;
        String name = nameField.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(name.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        int employeeid = Integer.parseInt(employeeidField.getText());
        if(employeeid == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        int age = Integer.parseInt(ageField.getText());
        if(age == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        
        // Using Java Swing Component Datepicker to get date value.
        Date sdate = startDatePicker.getDate();
        String pattern = "MM-dd-yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String startdate = simpleDateFormat.format(sdate);

        if(startdate.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        int level = Integer.parseInt(levelField.getText());
        if(level == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        String teaminfo = teaminfoField.getText();
        if(teaminfo.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(teaminfo.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        String title = titleField.getText();
        if(title.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(title.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        String phone = phonenumberField.getText();
        if(phone.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(phone.length()>10 | phone.length() < 10){
            JOptionPane.showMessageDialog(this,"Please enter a 10 digit value.");
            val++;
        }
        String email = emailField.getText();
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(email.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        if(!email.contains("@")){
            JOptionPane.showMessageDialog(this,"Please enter a valid email address.");
            val++;
        }
        String path = imagepathField.getText();
        
        // If any Validation fails, input is not added to the Jtable.
        if(val==0){
            // Calling function to insert element to arraylist.
            Employee emp = directory.addnewEmployees();

            emp.setName(name);
            emp.setEmployeeId(employeeid);
            emp.setAge(age);
            // Checking which radiobutton is selected for Gender.
            if((mRadioButton.isSelected())){
                emp.setGender("male");
            }
            else{
                emp.setGender("female");
            }
            emp.setStartdate(startdate);
            emp.setLevel(level);
            emp.setTeaminfo(teaminfo);
            emp.setTitle(title);
            emp.setPhone(phone);
            emp.setEmail(email);
            emp.setImagepath(path);

            JOptionPane.showMessageDialog(this,"New Employee Details saved successfully!!!");

            // Resetting textfield values.
            nameField.setText("");
            employeeidField.setText("");
            ageField.setText("");
            levelField.setText("");
            teaminfoField.setText("");
            titleField.setText("");
            phonenumberField.setText("");
            emailField.setText("");
        }

    }//GEN-LAST:event_saveButtonActionPerformed
    
    // Function Code for Uploading Images.
    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser imagefile = new JFileChooser();

        FileNameExtensionFilter fnf = new FileNameExtensionFilter("png","jpeg");
        imagefile.addChoosableFileFilter(fnf);
        int showDialog = imagefile.showOpenDialog(null);
        if(showDialog == JFileChooser.APPROVE_OPTION){
            File selectedimage = imagefile.getSelectedFile();
            String selectedimagepath = selectedimage.getAbsolutePath();
            imagepathField.setText(String.valueOf(selectedimagepath));
            if(selectedimagepath.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Re-upload the Image.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Image Uploaded Successfully.");
            }
        }

    }//GEN-LAST:event_imageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField employeeidField;
    private javax.swing.JLabel employeeidLabel;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton imageButton;
    private javax.swing.JTextField imagepathField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phonenumberField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JButton saveButton;
    private org.jdesktop.swingx.JXDatePicker startDatePicker;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JTextField teaminfoField;
    private javax.swing.JLabel teaminfoLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
