/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeDirectory;

/**
 *
 * @author ashwini
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    // Creating reference variable for ArrayList.
    EmployeeDirectory directory;
    
    public SearchJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        sbyIDButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        phonenumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phonenumberField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        teaminfoLabel = new javax.swing.JLabel();
        imagepathLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        imagepathField = new javax.swing.JTextField();
        employeeidField = new javax.swing.JTextField();
        levelField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        teaminfoField = new javax.swing.JTextField();
        employeeidLabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        startdateField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Employee Details");

        sbyIDButton.setText("Search");
        sbyIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbyIDButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search by :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EmployeeName", "EmployeeId", "Title", "Teaminfo" }));

        phonenumberLabel.setText("Contact:");

        emailLabel.setText("Email :");

        teaminfoLabel.setText("Team Info:");

        imagepathLabel.setText("Image Path:");

        titleLabel.setText("Title:");

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel.setText("Name:");

        genderLabel.setText("Gender:");

        employeeidLabel.setText("EmployeeId:");

        startdateLabel.setText("Start Date:");

        ageLabel.setText("Age:");

        levelLabel.setText("Level:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(employeeidLabel)
                                            .addComponent(genderLabel)
                                            .addComponent(ageLabel)
                                            .addComponent(startdateLabel)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(206, 206, 206)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailLabel)
                                            .addComponent(imagepathLabel)
                                            .addComponent(phonenumberLabel)
                                            .addComponent(titleLabel)
                                            .addComponent(teaminfoLabel)
                                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(startdateField)
                                    .addComponent(employeeidField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField)
                                    .addComponent(teaminfoField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phonenumberField)
                                    .addComponent(emailField)
                                    .addComponent(imagepathField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(searchLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sbyIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbyIDButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(employeeidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startdateLabel))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teaminfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teaminfoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel)))
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(employeeidLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagepathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagepathLabel))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Function to search button.
    private void sbyIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbyIDButtonActionPerformed
        // TODO add your handling code here:
        
        // To get value selected from drop down for SearchBy - 1. Employeename , 2. EmployeeId ,
        //3. Title , 4. Team Info
        String selectedfield = jComboBox1.getSelectedItem().toString();

        // Check if user is searching by EmployeeName
        if(selectedfield.equals("EmployeeName")){
            String name = searchField.getText();
            searchEmployeebyName(name);
            searchField.setText("");
        }
        // Check if user is searching by EmployeeId
        else if(selectedfield.equals("EmployeeId")){
            int id = Integer.parseInt(searchField.getText());
            searchEmployeebyID(id);
            searchField.setText("");
        }
        // Check if user is searching by Title
        else if(selectedfield.equals("Title")){
            String title = searchField.getText();
            searchEmployeebyTitle(title);
            searchField.setText("");
        }
        // Check if  user is searching by Team Info
        else if(selectedfield.equals("Teaminfo")){
            String tinfo = searchField.getText();
            searchEmployeebyTeaminfo(tinfo);
            searchField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter name or Id of employee to search.");
        }
    }//GEN-LAST:event_sbyIDButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField employeeidField;
    private javax.swing.JLabel employeeidLabel;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagepathField;
    private javax.swing.JLabel imagepathLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phonenumberField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JButton sbyIDButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField startdateField;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JTextField teaminfoField;
    private javax.swing.JLabel teaminfoLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    // Function Code for Searching by Employee name
    private void searchEmployeebyName(String name) {
        for (Employee emp:directory.getDirectory()){
                if(emp.getName().equals(name)){
                    nameField.setText(String.valueOf(emp.getName()));
                    employeeidField.setText(String.valueOf(emp.getEmployeeId()));
                    ageField.setText(String.valueOf(emp.getAge()));
                    genderField.setText(String.valueOf(emp.getGender()));
                    startdateField.setText(String.valueOf(emp.getStartdate()));
                    levelField.setText(String.valueOf(emp.getLevel()));
                    teaminfoField.setText(String.valueOf(emp.getTeaminfo()));
                    titleField.setText(String.valueOf(emp.getTitle()));
                    phonenumberField.setText(String.valueOf(emp.getPhone()));
                    emailField.setText(String.valueOf(emp.getEmail()));
                    imagepathField.setText(String.valueOf(emp.getImagepath()));
                    String imgpath = emp.getImagepath();

                    ImageIcon img = new ImageIcon(imgpath);
                    Image image = img.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

                    imageLabel.setIcon(new ImageIcon(image));
                }
            }
    }

    // Function Code for searching by EmployeeId
    private void searchEmployeebyID(int id) {
        for (Employee emp:directory.getDirectory()){
                if(emp.getEmployeeId() == id){
                    nameField.setText(String.valueOf(emp.getName()));
                    employeeidField.setText(String.valueOf(emp.getEmployeeId()));
                    ageField.setText(String.valueOf(emp.getAge()));
                    genderField.setText(String.valueOf(emp.getGender()));
                    startdateField.setText(String.valueOf(emp.getStartdate()));
                    levelField.setText(String.valueOf(emp.getLevel()));
                    teaminfoField.setText(String.valueOf(emp.getTeaminfo()));
                    titleField.setText(String.valueOf(emp.getTitle()));
                    phonenumberField.setText(String.valueOf(emp.getPhone()));
                    emailField.setText(String.valueOf(emp.getEmail()));
                    imagepathField.setText(String.valueOf(emp.getImagepath()));
                    String imgpath = emp.getImagepath();

                    ImageIcon img = new ImageIcon(imgpath);
                    Image image = img.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

                    imageLabel.setIcon(new ImageIcon(image));
                }
            }
    }

    // Function code for searching by Title
    private void searchEmployeebyTitle(String title) {
        for (Employee emp:directory.getDirectory()){
                if(emp.getTitle().equals(title)){
                    nameField.setText(String.valueOf(emp.getName()));
                    employeeidField.setText(String.valueOf(emp.getEmployeeId()));
                    ageField.setText(String.valueOf(emp.getAge()));
                    genderField.setText(String.valueOf(emp.getGender()));
                    startdateField.setText(String.valueOf(emp.getStartdate()));
                    levelField.setText(String.valueOf(emp.getLevel()));
                    teaminfoField.setText(String.valueOf(emp.getTeaminfo()));
                    titleField.setText(String.valueOf(emp.getTitle()));
                    phonenumberField.setText(String.valueOf(emp.getPhone()));
                    emailField.setText(String.valueOf(emp.getEmail()));
                    imagepathField.setText(String.valueOf(emp.getImagepath()));
                    String imgpath = emp.getImagepath();

                    ImageIcon img = new ImageIcon(imgpath);
                    Image image = img.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

                    imageLabel.setIcon(new ImageIcon(image));
                }
            }
    }

    // Function code for searching by Team Info.
    private void searchEmployeebyTeaminfo(String tinfo) {
        for (Employee emp:directory.getDirectory()){
                if(emp.getTeaminfo().equals(tinfo)){
                    nameField.setText(String.valueOf(emp.getName()));
                    employeeidField.setText(String.valueOf(emp.getEmployeeId()));
                    ageField.setText(String.valueOf(emp.getAge()));
                    genderField.setText(String.valueOf(emp.getGender()));
                    startdateField.setText(String.valueOf(emp.getStartdate()));
                    levelField.setText(String.valueOf(emp.getLevel()));
                    teaminfoField.setText(String.valueOf(emp.getTeaminfo()));
                    titleField.setText(String.valueOf(emp.getTitle()));
                    phonenumberField.setText(String.valueOf(emp.getPhone()));
                    emailField.setText(String.valueOf(emp.getEmail()));
                    imagepathField.setText(String.valueOf(emp.getImagepath()));
                    String imgpath = emp.getImagepath();

                    ImageIcon img = new ImageIcon(imgpath);
                    Image image = img.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

                    imageLabel.setIcon(new ImageIcon(image));
                }
            }
    }

    
}
