/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.EmployeeDirectory;

/**
 *
 * @author ashwini
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    // Creating reference variable for ArrayList.
    EmployeeDirectory directory;
    
    public ViewJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        levelLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        teaminfoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        employeeidField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        employeeidLabel = new javax.swing.JLabel();
        startdateField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phonenumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phonenumberField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        imagepathLabel = new javax.swing.JLabel();
        levelField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        imagepathField = new javax.swing.JTextField();
        teaminfoField = new javax.swing.JTextField();
        startdateLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Employee Details");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "EmployeeId", "Age", "Gender", "Start date", "Level", "Team Info", "Title", "PhoneNumber", "Email", "Image Pathl"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(825, 80));
        jScrollPane1.setViewportView(jTable1);

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        levelLabel.setText("Level:");

        teaminfoLabel.setText("Team Info:");

        titleLabel.setText("Title :");

        nameLabel.setText("Name:");

        employeeidLabel.setText("EmployeeId:");

        ageLabel.setText("Age:");

        phonenumberLabel.setText("Contact:");

        emailLabel.setText("Email:");

        imagepathLabel.setText("Image Path:");

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        genderLabel.setText("Gender:");

        startdateLabel.setText("Start Date:");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(imagepathLabel)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailLabel)
                                                    .addComponent(titleLabel)
                                                    .addComponent(phonenumberLabel)))
                                            .addComponent(ageLabel)
                                            .addComponent(genderLabel)
                                            .addComponent(startdateLabel)
                                            .addComponent(levelLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(nameLabel)))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(employeeidLabel)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(teaminfoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(genderField)
                            .addComponent(phonenumberField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teaminfoField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levelField)
                            .addComponent(titleField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagepathField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startdateField)
                            .addComponent(employeeidField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(222, 222, 222)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addGap(12, 12, 12)
                .addComponent(updateButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeidLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startdateLabel)
                            .addComponent(startdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaminfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teaminfoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagepathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagepathLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Function code for View button.
    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int rowindex = jTable1.getSelectedRow();

        if(rowindex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view.");
            return;
        }
        
        // Creating JTable model variable to put/get values from/into JTable.
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Employee selectedemp = (Employee) model.getValueAt(rowindex, 0);

        // Getting values from Textfield and adding Arraylist reference to them.
        nameField.setText(String.valueOf(selectedemp.getName()));
        employeeidField.setText(String.valueOf(selectedemp.getEmployeeId()));
        ageField.setText(String.valueOf(selectedemp.getAge()));
        genderField.setText(String.valueOf(selectedemp.getGender()));
        startdateField.setText(String.valueOf(selectedemp.getStartdate()));
        levelField.setText(String.valueOf(selectedemp.getLevel()));
        teaminfoField.setText(String.valueOf(selectedemp.getTeaminfo()));
        titleField.setText(String.valueOf(selectedemp.getTitle()));
        phonenumberField.setText(String.valueOf(selectedemp.getPhone()));
        emailField.setText(String.valueOf(selectedemp.getEmail()));
        imagepathField.setText(String.valueOf(selectedemp.getImagepath()));
        String imgpath = selectedemp.getImagepath();
        
        // Using Imageicon to display image using image path.
        ImageIcon img = new ImageIcon(imgpath);
        Image image = img.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

        imageLabel.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_viewButtonActionPerformed

    // Function Code for Update button.
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        // Creating JTable model to get values from the selected row in Jtable.
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowindex = jTable1.getSelectedRow();
        
        // Creating new variables to store new updated Text Field values.
        String newname = nameField.getText();
        int newemployeeid = Integer.parseInt(employeeidField.getText());
        int newage = Integer.parseInt(ageField.getText());
        String newgender = genderField.getText();
        String newstartdate = startdateField.getText();
        int newlevel = Integer.parseInt(levelField.getText());
        String newteaminfo = teaminfoField.getText();
        String newtitle = titleField.getText();
        String newphonenumber = phonenumberField.getText();
        String newemail = emailField.getText();
        
        // Calling UpdateEmployee function to add updated values to Array list.
        Employee emp = directory.updateEmployee(rowindex);
        
        // Setting new values and linking it to employeeDirectory reference.
        emp.setName(newname);
        emp.setEmployeeId(newemployeeid);
        emp.setAge(newage);
        emp.setGender(newgender);
        emp.setStartdate(newstartdate);
        emp.setLevel(newlevel);
        emp.setTeaminfo(newteaminfo);
        emp.setTitle(newtitle);
        emp.setPhone(newphonenumber);
        emp.setEmail(newemail);

        // Adding new input values to the JTable for selectedrow.
        model.setValueAt(newname, rowindex, 0);
        model.setValueAt(newemployeeid, rowindex, 1);
        model.setValueAt(newage, rowindex, 2);
        model.setValueAt(newgender, rowindex, 3);
        model.setValueAt(newstartdate, rowindex, 4);
        model.setValueAt(newlevel, rowindex, 5);
        model.setValueAt(newteaminfo, rowindex, 6);
        model.setValueAt(newtitle, rowindex, 7);
        model.setValueAt(newphonenumber, rowindex, 8);
        model.setValueAt(newemail, rowindex, 9);

        // Calling function to display values added to JTable.
        populateTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    // Function Code for delete button.
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        // Getting row index value to delete.
        int rowindex = jTable1.getSelectedRow();

        // Check if user has selected a row to delete.
        if(rowindex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Employee selectedemp = (Employee) model.getValueAt(rowindex, 0);

        // Calling function to delete element in arraylist directory.
        directory.deleteEmployee(selectedemp);

        JOptionPane.showMessageDialog(this, "Selected Employee Record is deleted.");

        // Calling Function to display table.
        populateTable();
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField employeeidField;
    private javax.swing.JLabel employeeidLabel;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagepathField;
    private javax.swing.JLabel imagepathLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phonenumberField;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JTextField startdateField;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JTextField teaminfoField;
    private javax.swing.JLabel teaminfoLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables

    // Function to display table values.
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (Employee emp:directory.getDirectory()){
            Object[] row = new Object[11];
            row[0] = emp;
            row[1] = emp.getName();
            row[1] = emp.getEmployeeId();
            row[2] = emp.getAge();
            row[3] = emp.getGender();
            row[4] = emp.getStartdate();
            row[5] = emp.getLevel();
            row[6] = emp.getTeaminfo();
            row[7] = emp.getTitle();
            row[8] = emp.getPhone();
            row[9] = emp.getEmail();
            row[10]= emp.getImagepath();
            model.addRow(row);
        }
    }
}
