/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui;

import datamodel.DataManager;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.DoctorDirectory;
import model.Doctor;
import model.Person;

/**
 *
 * @author ashwini
 */
public class adddoctorJPanel extends javax.swing.JPanel {

    /** Creates new form adddoctorJPanel */
    //DoctorDirectory doctors;
    JPanel cards;
    CardLayout cl;
    
    public adddoctorJPanel(JPanel cards) {
        
        this.cards = cards;
        this.cl =  (CardLayout)cards.getLayout();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        fRadioButton = new javax.swing.JRadioButton();
        emailField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        pidField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        pnameField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        pnameLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        pIDLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        mRadioButton = new javax.swing.JRadioButton();
        ptypeField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Doctor Data ");

        emailLabel.setText("Email  :");

        fRadioButton.setText("Female");

        contactLabel.setText("Contact:");

        genderLabel.setText("Gender");

        ageLabel.setText("Age:");

        addressLabel.setText("Address : ");

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        cityLabel.setText("City : ");

        pnameLabel.setText("Name :");

        pIDLabel.setText("Doctor ID :");

        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        typeLabel.setText("Speciality : ");

        mRadioButton.setText("Male");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactLabel)
                        .addGap(57, 57, 57)
                        .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(cityLabel)
                            .addComponent(addressLabel)
                            .addComponent(emailLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ptypeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pIDLabel)
                                .addComponent(pnameLabel)
                                .addComponent(genderLabel)
                                .addComponent(ageLabel))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ageField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(pidField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnameField, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(backButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(saveButton)))
                    .addContainerGap(388, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel))))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnameLabel)
                        .addComponent(pnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pIDLabel)
                        .addComponent(pidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageLabel)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mRadioButton)
                            .addComponent(fRadioButton)))
                    .addGap(250, 250, 250)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton)
                        .addComponent(backButton))
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int val = 0;
        String pname = pnameField.getText();
        if(pname.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(pname.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        int pid = Integer.parseInt(pidField.getText());
        try{
            if(pid == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,nfe.getMessage());
        }
        int age = Integer.parseInt(ageField.getText());
        try{
            if(age == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,nfe.getMessage());
        }
        String contact = contactField.getText();
        if(contact.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(contact.length() > 10 | contact.length() > 10){
            JOptionPane.showMessageDialog(this,"Please enter a 10 digit value");
            val++;
        }
        String email = emailField.getText();
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(!email.contains("@")){
            JOptionPane.showMessageDialog(this,"Please enter valid email");
            val++;
        }
        String address = addressField.getText();
        if(address.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(address.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        String city = cityField.getText();
        if(city.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(city.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        String ptype = ptypeField.getText();
        if(ptype.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(ptype.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        Person per = new Person();
        
        Doctor doc = new Doctor(per);
        per.setName(pname);
        per.setId(pid);
        per.setAge(age);
        per.setContact(contact);
        per.setEmail(email);
        per.setAddress(address);
        per.setCity(city);
        
        
        if((mRadioButton.isSelected())){
            per.setGender("male");
        }
        else{
            per.setGender("female");
        }

        DataManager.shared.doctors.addnewdoctor(doc);
       

        JOptionPane.showMessageDialog(this,"New Doctor Details saved successfully!!!");

        pnameField.setText("");
        pidField.setText("");
        ageField.setText("");
        contactField.setText("");
        emailField.setText("");
        addressField.setText("");
        cityField.setText("");
        ptypeField.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cl.previous(cards);
        cards.remove(this);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField contactField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JLabel pIDLabel;
    private javax.swing.JTextField pidField;
    private javax.swing.JTextField pnameField;
    private javax.swing.JLabel pnameLabel;
    private javax.swing.JTextField ptypeField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

}
