/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import datamodel.DataManager;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Encounter;
import model.VitalSigns;

/**
 *
 * @author ashwini
 */
public class addencounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addencounterJPanel
     */
    //Encounterhistory history;
    JPanel cards;
    CardLayout cl;
    
    
    public addencounterJPanel(JPanel cards) {
        initComponents();
        this.cards = cards;
        this.cl =  (CardLayout)cards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        visitdateLabel = new javax.swing.JLabel();
        visitdatePicker = new org.jdesktop.swingx.JXDatePicker();
        saveButton = new javax.swing.JButton();
        vtypeLabel = new javax.swing.JLabel();
        vtypeField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vdocField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pidField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Patient Encounter");

        visitdateLabel.setText("Visit Date :");

        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        vtypeLabel.setText("Visit type : ");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Visiting Doctor ID: ");

        jLabel3.setText("Patient ID : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtypeLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(visitdatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vtypeField)
                            .addComponent(vdocField)
                            .addComponent(pidField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitdateLabel)
                    .addComponent(visitdatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vdocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vtypeLabel)
                    .addComponent(vtypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(backButton))
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        int val = 0;
        Date sdate = visitdatePicker.getDate();
        String pattern = "MM-dd-yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String visitdate = simpleDateFormat.format(sdate);
        
        int pid = Integer.parseInt(pidField.getText());
        try{
            if(pid == 0){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,nfe.getMessage());
        }
        int vdoc = Integer.parseInt(vdocField.getText());
        
        String vtype = vtypeField.getText();
        if(vtype.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter input");
            val++;
        }
        if(vtype.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this,"Please enter a string value.");
            val++;
        }
        
        if(val == 0){
            VitalSigns vs = new VitalSigns();
            Encounter e = new Encounter(vs);

            e.doctor = DataManager.shared.doctors.fetchDoctor(vdoc);
            e.p = DataManager.shared.patients.fetchPatientbyID(pid);

            //e.doctor.getPerson().setId(vdoc);
            e.setVisitdate(visitdate);
            e.setVisittype(vtype);
            DataManager.shared.history.addnewencounter(e);





            JOptionPane.showMessageDialog(this,"New Encounter Details saved successfully!!!");

            vtypeField.setText("");
        }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cl.previous(cards);
        cards.remove(this);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pidField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField vdocField;
    private javax.swing.JLabel visitdateLabel;
    private org.jdesktop.swingx.JXDatePicker visitdatePicker;
    private javax.swing.JTextField vtypeField;
    private javax.swing.JLabel vtypeLabel;
    // End of variables declaration//GEN-END:variables
}
