/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.awt.CardLayout;
import javax.swing.JPanel;
import model.*;
/**
 *
 * @author ashwini
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    
    PatientDirectory patients;
    DoctorDirectory doctors;
    Encounterhistory history;
    JPanel cards;
    CardLayout cl;
    
    public PatientJPanel(PatientDirectory p,Encounterhistory hist, DoctorDirectory doc, JPanel cards) {
        this.patients = p;
        this.doctors = doc;
        this.history = hist;
        this.cards = cards;
        this.cl = (CardLayout) cards.getLayout();
        initComponents();
    }
    public PatientJPanel(PatientDirectory p, DoctorDirectory doc, JPanel cards) {
        this.patients = p;
        this.doctors = doc;
        this.cards = cards;
        this.cl = (CardLayout) cards.getLayout();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        vappointButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Patient ");

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Request Appointment ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vappointButton.setBackground(new java.awt.Color(51, 0, 255));
        vappointButton.setText("View Appointment History");
        vappointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vappointButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(vappointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vappointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BookappJPanel vpanel = new BookappJPanel(cards);
        cards.add(vpanel,"viewPatientHistoryPanel");
        cl.next(cards);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vappointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vappointButtonActionPerformed
        // TODO add your handling code here:
        ViewappJPanel vapanel = new ViewappJPanel(cards);
        cards.add(vapanel,"viewPatientAppointmentHistory");
        cl.next(cards);
    }//GEN-LAST:event_vappointButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vappointButton;
    // End of variables declaration//GEN-END:variables
}
