/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.PatientDirectory;
import model.Encounterhistory;
import model.Encounter;
import model.Patient;

/**
 *
 * @author ashwini
 */
public class viewPathistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPathistoryJPanel
     */
    PatientDirectory patients;
    Encounterhistory history;
    JPanel cards;
    CardLayout cl;
    
    public viewPathistoryJPanel(PatientDirectory pat , Encounterhistory hist , JPanel cards) {
        initComponents();
        this.patients = pat;
        this.history = hist;
        this.cards = cards;
        this.cl =  (CardLayout)cards.getLayout();
        PopulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patient History");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Age", "Gender", "Height", "Weight", "Temperature", "Blood Pressure", "Pulse", "Diagnosis", "Medication"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Patient History", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Visit Date", "EncounterID", "Visiting Doctor Name", "Last Visit Date", "Visit Type"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane2.addTab("Visit History", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Visit History");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void PopulateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (Patient pat: patients.getPatient()){
            Object[] row = new Object[11];
            row[0] = pat;
            row[1] = pat.getPatient().getName();
            row[1] = pat.getPatient().getId();
            row[2] = pat.getPatient().getAge();
            row[3] = pat.getPatient().getGender();
            row[4] = pat.getVitalsigns().getVisitdate();
            row[5] = pat.getVitalsigns().getHeight();
            row[6] = pat.getVitalsigns().getWeight();
            row[7] = pat.getVitalsigns().getTemperature();
            row[8] = pat.getVitalsigns().getBloodpressure();
            row[9] = pat.getVitalsigns().getPulse();
            row[10]= pat.getEncounter().getDiagnosis();
            model.addRow(row);
            
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        model2.setRowCount(0);
        
        for (Encounter enc: history.getHistory()){
            Object[] row2 = new Object[11];
            row2[0] = enc;
            row2[1] = enc.getVisitdate();
            row2[2] = enc.getEncounterid();
            row2[3] = enc.getVisitingdoctor();
            row2[4] = enc.getLastvisitdate();
            row2[5] = enc.getVisittype();
            model2.addRow(row);
    }
        }
    }
}
