/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author ashwini
 */
public class viewpersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewpersonJPanel
     */
    
    PersonDirectory pd ;
    JPanel cards;
    CardLayout cl;
    
    public viewpersonJPanel(PersonDirectory p, JPanel cards) {
        initComponents();
        this.pd = p;
        this.cards = cards;
        this.cl =  (CardLayout)cards.getLayout();
        PopulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        visitdateLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        ptypeField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        pidField = new javax.swing.JTextField();
        ptypeLabel = new javax.swing.JLabel();
        pnameField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        pnameLabel = new javax.swing.JLabel();
        visitdateField = new javax.swing.JTextField();
        pIDLabel = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patient Details");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "PersonId", "Age", "Gender", "Visit Date", "Contact", "Email", "Address", "City", "Relation with patient"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(825, 80));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Age :");

        contactLabel.setText("Contact :");

        visitdateLabel.setText("Visit Date :");

        emailLabel.setText("Email  :");

        genderLabel.setText("Gender");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        addressLabel.setText("Address :");

        CityLabel.setText("City : ");

        ptypeLabel.setText("Relation with Patient : ");

        pnameLabel.setText("Person name :");

        visitdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitdateFieldActionPerformed(evt);
            }
        });

        pIDLabel.setText("Person ID :");

        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(backButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pIDLabel)
                            .addComponent(pnameLabel))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pidField)
                            .addComponent(pnameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptypeLabel)
                            .addComponent(CityLabel)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel)
                            .addComponent(jLabel2)
                            .addComponent(contactLabel)
                            .addComponent(emailLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField)
                            .addComponent(addressField)
                            .addComponent(cityField)
                            .addComponent(ptypeField)
                            .addComponent(contactField)
                            .addComponent(visitdateField)
                            .addComponent(genderField)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnameLabel)
                            .addComponent(pnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pIDLabel)
                            .addComponent(pidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitdateLabel)
                            .addComponent(visitdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactLabel)
                            .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CityLabel)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptypeLabel)
                            .addComponent(ptypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int rowindex = jTable1.getSelectedRow();

        if(rowindex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Person selectedp = (Person) model.getValueAt(rowindex, 0);

        pnameField.setText(String.valueOf(selectedp.getName()));
        pidField.setText(String.valueOf(selectedp.getId()));
        ageField.setText(String.valueOf(selectedp.getAge()));
        genderField.setText(String.valueOf(selectedp.getGender()));
        visitdateField.setText(String.valueOf(selectedp.getVisit_date()));
        contactField.setText(String.valueOf(selectedp.getContact()));
        emailField.setText(String.valueOf(selectedp.getEmail()));
        addressField.setText(String.valueOf(selectedp.getAddress()));
        cityField.setText(String.valueOf(selectedp.getCity()));
        ptypeField.setText(String.valueOf(selectedp.getPtype()));

    }//GEN-LAST:event_viewButtonActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void visitdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitdateFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_visitdateFieldActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowindex = jTable1.getSelectedRow();

        String newname = pnameField.getText();
        int newid = Integer.parseInt(pidField.getText());
        int newage = Integer.parseInt(ageField.getText());
        String newgender = genderField.getText();
        String newvisitdate = visitdateField.getText();
        String contact = contactField.getText();
        String email = emailField.getText();
        String address = addressField.getText();
        String city = cityField.getText();
        String ptype = ptypeField.getText();

        Person pat = pd.updateperson(rowindex);

        pat.setName(newname);
        pat.setId(newid);
        pat.setAge(newage);
        pat.setGender(newgender);
        pat.setVisit_date(newvisitdate);
        pat.setContact(contact);
        pat.setEmail(email);
        pat.setAddress(address);
        pat.setCity(city);
        pat.setPtype(ptype);

        model.setValueAt(newname, rowindex, 0);
        model.setValueAt(newid, rowindex, 1);
        model.setValueAt(newage, rowindex, 2);
        model.setValueAt(newgender, rowindex, 3);
        model.setValueAt(newvisitdate, rowindex, 4);
        model.setValueAt(contact, rowindex, 5);
        model.setValueAt(email, rowindex, 6);
        model.setValueAt(address, rowindex, 7);
        model.setValueAt(city, rowindex, 8);
        model.setValueAt(ptype, rowindex, 9);

        PopulateTable();

    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        int rowindex = jTable1.getSelectedRow();

        if(rowindex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Person selectedp = (Person) model.getValueAt(rowindex, 0);

        pd.deleteperson(selectedp);

        JOptionPane.showMessageDialog(this, "Selected Person Record is deleted.");

        pnameField.setText("");
        pidField.setText("");
        ageField.setText("");
        genderField.setText("");
        visitdateField.setText("");
        contactField.setText("");
        emailField.setText("");
        addressField.setText("");
        cityField.setText("");
        ptypeField.setText("");

        PopulateTable();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        cl.previous(cards);
        cards.remove(this);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField contactField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pIDLabel;
    private javax.swing.JTextField pidField;
    private javax.swing.JTextField pnameField;
    private javax.swing.JLabel pnameLabel;
    private javax.swing.JTextField ptypeField;
    private javax.swing.JLabel ptypeLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    private javax.swing.JTextField visitdateField;
    private javax.swing.JLabel visitdateLabel;
    // End of variables declaration//GEN-END:variables

    private void PopulateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (Person pat: pd.getPersons()){
            Object[] row = new Object[11];
            row[0] = pat;
            row[1] = pat.getName();
            row[1] = pat.getId();
            row[2] = pat.getAge();
            row[3] = pat.getGender();
            row[4] = pat.getVisit_date();
            row[5] = pat.getContact();
            row[6] = pat.getEmail();
            row[7] = pat.getAddress();
            row[8] = pat.getCity();
            row[9] = pat.getPtype();
            model.addRow(row);
    }
}
}
